#!/bin/bash -e
#
# Test the Dockerfile.tools image.
#
# IMAGE_NAME specifies the name of the candidate image used for testing.
# The image has to be available before this script is executed.
#
BUILD_TOOL="${BUILD_TOOL:-podman}"
WORK_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

${BUILD_TOOL} run --rm --entrypoint=/bin/sh ${IMAGE_NAME} -c 'operator-sdk version'
${BUILD_TOOL} run --rm --entrypoint=/bin/sh ${IMAGE_NAME} -c 'go version'

${BUILD_TOOL} run --rm -u $UID -v "${WORK_DIR}/../..:/cloud-resource-operator:z" --entrypoint=/bin/sh ${IMAGE_NAME} -c "cd /cloud-resource-operator && make vendor/check"
${BUILD_TOOL} run --rm -u $UID -v "${WORK_DIR}/../..:/cloud-resource-operator:z" --entrypoint=/bin/sh ${IMAGE_NAME} -c "cd /cloud-resource-operator && make code/check"
${BUILD_TOOL} run --rm -u $UID -v "${WORK_DIR}/../..:/cloud-resource-operator:z" --entrypoint=/bin/sh ${IMAGE_NAME} -c "cd /cloud-resource-operator && make build"
${BUILD_TOOL} run --rm -u $UID -v "${WORK_DIR}/../..:/cloud-resource-operator:z" --entrypoint=/bin/sh ${IMAGE_NAME} -c "cd /cloud-resource-operator && make test/unit"

echo "SUCCESS!"
